### ISSUE TITLE
V3 Roadmap

### ISSUE THREAD

**Issue by jdecool** [novaway/NovawayFeatureFlagBundle#32]
- [x] Remove all deprecated methods (https://github.com/novaway/NovawayFeatureFlagBundle/pull/33)
- [x] Replace `enabled` flag in feature model by an expression evaluated by the Symfony ExpressoinLanguage for more flexibility
- [x] Coding Standard: remove usage of the `Interface` suffix
- [x] Remove support for unmaintained Symfony version (>= 5.4) (https://github.com/novaway/NovawayFeatureFlagBundle/pull/33)
- [x] Remove support for unmaintained PHP version (>= 8.0) (https://github.com/novaway/NovawayFeatureFlagBundle/pull/44)
- [x] Migrate bundle configuration to PHP format version (and remove `symfony/yaml` dependency) (https://github.com/novaway/NovawayFeatureFlagBundle/pull/34)
- [x] Remove annotation support (support only attributes) (https://github.com/novaway/NovawayFeatureFlagBundle/pull/42)
